# From:
# https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis/gap/pad-us-data-manual
# Table 8. Designation Type domain codes and descriptions
DESIGNATION_TYPES = {
    'ACC': 'Access Area',
    'ACEC': 'Area of Critical Environmental Concern',
    # 'AGRE': 'Agricultural Easement',
    'CONE': 'Conservation Easement',
    'FORE': 'Forest Stewardship Easement',
    # 'FOTH': 'Federal Other or Unknown Designation',
    # 'HCA': 'Historic or Cultural Area',
    # 'HCAE': 'Historic or Cultural Easement',
    # 'IRA': 'Inventoried Roadless Area',
    # 'LCA': 'Local Conservation Area',
    # 'LHCA': 'Local Historic or Cultural Area',
    # 'LOTH': 'Local Other or Unknown',
    # 'LP': 'Local Park',
    # 'LREC': 'Local Recreation Area',
    # 'LRMA': 'Local Resource Management Area',
    # 'MIL': 'Military Land',
    # 'MIT': 'Mitigation Land or Bank',
    'MPA': 'Marine Protected Area',
    'NCA': 'Conservation Area',
    # 'ND': 'Not Designated',
    'NF': 'National Forest',
    'NG': 'National Grassland',
    'NLS': 'National Lakeshore or Seashore',
    'NM': 'National Monument',
    'NP': 'National Park',
    'NRA': 'National Recreation Area',
    'NSBV': 'National Scenic, Botanical or Volcanic Area',
    'NT': 'National Scenic or Historic Trail',
    'NWR': 'National Wildlife Refuge',
    # 'OCS': 'Outer Continental Shelf Area',
    # 'OTHE': 'Other Easement',
    # 'PAGR': 'Private Agricultural',
    # 'PCON': 'Private Conservation',
    # 'PFOR': 'Private Forest Stewardship',
    # 'PHCA': 'Private Historic or Cultural',
    # 'POTH': 'Private Other or Unknown',
    # 'PPRK': 'Private Park',
    # 'PRAN': 'Private Ranch',
    # 'PREC': 'Private Recreation or Education',
    'PROC': 'Approved or Proclamation Boundary',
    'PUB': 'National Public Lands',
    # 'RANE': 'Ranch Easement',
    'REA': 'Research or Educational Area',
    'REC': 'Recreation Management Area',
    'RECE': 'Recreation or Education Easement',
    # 'RMA': 'Resource Management Area',
    'RNA': 'Research Natural Area',
    'SCA': 'State Conservation Area',
    # 'SDA': 'Special Designation Area',
    # 'SHCA': 'State Historic or Cultural Area',
    # 'SOTH': 'State Other or Unknown',
    'SP': 'State Park',
    'SREC': 'State Recreation Area',
    # 'SRMA': 'State Resource Management Area',
    'SW': 'State Wilderness',
    # 'TRIBL': 'Native American Land Area',
    # 'UNK': 'Unknown',
    # 'UNKE': 'Unknown Easement',
    'WA': 'Wilderness Area',
    # 'WPA': 'Watershed Protection Area',
    'WSA': 'Wilderness Study Area',
    'WSR': 'Wild and Scenic River',
}
